[package]
name = "iroh-live"
version = "0.1.0"
edition = "2024"
description = "audio and video live streaming over iroh"
authors = ["Franz Heinzmann <frando@n0.computer>"]
repository = "https://github.com/n0-computer/iroh-live"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.100"
bytemuck = "1.24.0"
data-encoding = "2.9.0"
derive_more = { version = "2.0.1", features = ["display", "debug"] }
ffmpeg-next = { version = "8.0.0", features = ["device", "format"] }
firewheel = { version = "0.9.1", features = ["cpal", "std", "stream_nodes"] }
hang = "0.6.1"
image = { version = "0.25.8", default-features = false }
iroh = "0.95.1"
iroh-tickets = "0.2.0"
moq-lite = "0.9.6"
n0-error = { version = "0.1.2", features = ["anyhow"] }
n0-future = "0.3.1"
nokhwa = { version = "0.10", features = [
    "input-native",
    "input-v4l",
    "output-threaded",
] }
postcard = "1.1.3"
rav1d = { git = "https://github.com/leo030303/rav1d", branch = "add-rust-api", version = "1.1.0", default-features = false, features = ["bitdepth_8"] }
rav1e = { version = "0.8.1", default-features = false, features = ["threading"] }
serde = { version = "1.0.228", features = ["derive"] }
strum = { version = "0.26", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.48.0", features = ["sync"] }
tokio-util = "0.7.17"
tracing = "0.1.41"
opus = "0.3"
url = "2.5.7"
web-transport-iroh = { version = "0.1.0", path = "../web-transport-iroh" }
xcap = "0.7.1"
yuv = "0.8.8"
byte-unit = "5.1"
n0-watcher = "0.6.0"
## removed duplicate strum

[dev-dependencies]
eframe = "0.33.0"
rand = "0.9.2"
tokio = { version = "1.48.0", features = ["full"] }
tracing-subscriber = "0.3.20"
