[package]
name = "iroh-live"
version = "0.1.0"
edition = "2024"
description = "audio and video live streaming over iroh"
authors = ["Franz Heinzmann <frando@n0.computer>"]
repository = "https://github.com/n0-computer/iroh-live"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.100"
bytemuck = "1.24.0"
byte-unit = { version = "5.1", features = ["bit"] }
data-encoding = "2.9.0"
derive_more = { version = "2.0.1", features = ["display", "debug"] }
ffmpeg-next = { version = "8.0.0", features = ["device", "format"] }
firewheel = { version = "0.9.1", features = ["cpal", "std", "stream_nodes"] }
hang = "0.6.1"
image = { version = "0.25.8", default-features = false }
iroh = "0.95.1"
iroh-moq = { path = "../iroh-moq" }
iroh-tickets = "0.2.0"
moq-lite = "0.9.6"
n0-error = { version = "0.1.2", features = ["anyhow"] }
n0-future = "0.3.1"
n0-watcher = "0.6.0"
nokhwa = { version = "0.10", features = [
    "input-native",
    "input-v4l",
    "output-threaded",
] }
postcard = "1.1.3"
serde = { version = "1.0.228", features = ["derive"] }
strum = { version = "0.26", features = ["derive"] }
tokio = { version = "1.48.0", features = ["sync"] }
tokio-util = "0.7.17"
tracing = "0.1.41"
xcap = "0.7.1"


[dev-dependencies]
clap = { version = "4.5", features = ["derive"] }
eframe = "0.33.0"
iroh-gossip = "0.95.0"
postcard = "1.1.3"
rand = "0.9.2"
tokio = { version = "1.48.0", features = ["full"] }
tracing-subscriber = "0.3.20"
